### ISSUE TITLE
输出的图片看不清

### ISSUE THREAD

**Issue by ElainaFanBoy** [NoNormalCreeper/nonebot_plugin_wolfram#3]
图太糊了

**Comment by NoNormalCreeper** [comment]
这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。

因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。

**Comment by ElainaFanBoy** [comment]
> 这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。
> 
> 因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。

太可惜了，但是插件还是很好用！期待以后可以更新

**Comment by NoNormalCreeper** [comment]
> > 这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。
> > 因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。
> 
> 太可惜了，但是插件还是很好用！期待以后可以更新

感谢你的认可 \(≧▽≦)/

另：该插件是我技术不成熟的时候编写的，存在一个致命bug，可能会导致堵塞。我在bot项目中修复过该bug，但忘记同步到这里来了。现在代码已同步过来，修复了该bug，建议重新下载插件并安装。

**Comment by ElainaFanBoy** [comment]
> > > 这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。
> > > 因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。
> > 
> > 太可惜了，但是插件还是很好用！期待以后可以更新
> 
> 感谢你的认可 \(≧▽≦)/
> 
> 另：该插件是我技术不成熟的时候编写的，存在一个致命bug，可能会导致堵塞。我在bot项目中修复过该bug，但忘记同步到这里来了。现在代码已同步过来，修复了该bug，建议重新下载插件并安装。

好的，辛苦了

**Comment by NoNormalCreeper** [comment]
> > > > 这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。
> > > > 因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。
> > > 
> > > 
> > > 太可惜了，但是插件还是很好用！期待以后可以更新
> > 
> > 
> > 感谢你的认可 (≧▽≦)/
> > 另：该插件是我技术不成熟的时候编写的，存在一个致命bug，可能会导致堵塞。我在bot项目中修复过该bug，但忘记同步到这里来了。现在代码已同步过来，修复了该bug，建议重新下载插件并安装。
> 
> 好的，辛苦了

很高兴能帮到你

**Comment by ElainaFanBoy** [comment]
> > > > > 这个问题有用户反馈过，我在一些群里询问过用户“图片是否清晰”并让他们给出截图。结果既有说糊的，也有说清晰的，截图清晰度也各不相同。
> > > > > 因此我不太清楚这个问题出现在哪里，故**暂时无法解决该问题**，非常抱歉。
> > > > 
> > > > 
> > > > 太可惜了，但是插件还是很好用！期待以后可以更新
> > > 
> > > 
> > > 感谢你的认可 (≧▽≦)/
> > > 另：该插件是我技术不成熟的时候编写的，存在一个致命bug，可能会导致堵塞。我在bot项目中修复过该bug，但忘记同步到这里来了。现在代码已同步过来，修复了该bug，建议重新下载插件并安装。
> > 
> > 
> > 好的，辛苦了
> 
> 很高兴能帮到你

时隔多日，我好像发现原因了...官方api输出的结果原来是gif格式的，好像是导致bot发送出去的格式属于[动画表情]，手机看可能会变糊很多（不太会py，还在学，不知道咋改代码）
![UF)62 O649BNH~R CUS(_9](https://user-images.githubusercontent.com/56375835/197203186-9082167b-ec58-4b57-a2ca-22ab1aef2cf1.png)

**Comment by NoNormalCreeper** [comment]
关于 GIF 转 PNG/JPG 格式，我找到了一些代码片段，但由于我的 bot 被封号，故目前无法进行测试，等我 bot 解封后我就会着手于此的。

**Comment by ElainaFanBoy** [comment]
草，我以为作者已经跑路了（）

**Comment by NoNormalCreeper** [comment]
> 草，我以为作者已经跑路了（）

没有啦，其实只是因为我一直没有建立新的bot号，加上高中学业比较繁忙，这段时间一直没去弄qq bot相关的技术了（

**Comment by ElainaFanBoy** [comment]
> > 草，我以为作者已经跑路了（）
> 
> 没有啦，其实只是因为我一直没有建立新的bot号，加上高中学业比较繁忙，这段时间一直没去弄qq bot相关的技术了（

您加油，学业为重，祝您学业有成

**Comment by NoNormalCreeper** [comment]
> > > 草，我以为作者已经跑路了（）
> > 
> > 
> > 没有啦，其实只是因为我一直没有建立新的bot号，加上高中学业比较繁忙，这段时间一直没去弄qq bot相关的技术了（
> 
> 您加油，学业为重，祝您学业有成

感谢祝福！如果您有了修改方案，欢迎修改后提交 pull request
